const fs = require('fs').promises;
const path = require('path');
const JSZip = require('jszip');

class Output {
    async createProjectStructure(data, baseDir) {
        const timestamp = Date.now();
        const projectName = data.overview?.projectName?.replace(/\s+/g, '-').toLowerCase() || 'project';
        const outputDir = path.join(baseDir, `${projectName}-${timestamp}`);

        // Create directory structure
        await fs.mkdir(outputDir, { recursive: true });
        await fs.mkdir(path.join(outputDir, 'code'), { recursive: true });
        await fs.mkdir(path.join(outputDir, 'docs'), { recursive: true });
        await fs.mkdir(path.join(outputDir, 'schematics'), { recursive: true });

        // Write code files
        if (data.codeSnippets && Array.isArray(data.codeSnippets)) {
            for (const file of data.codeSnippets) {
                const filePath = path.join(outputDir, 'code', file.filename);
                await fs.mkdir(path.dirname(filePath), { recursive: true });
                await fs.writeFile(filePath, file.code || '', 'utf8');
            }
        }

        // Write README
        const readme = this._generateReadme(data);
        await fs.writeFile(path.join(outputDir, 'README.md'), readme, 'utf8');

        // Write schematic
        if (data.schematic) {
            await fs.writeFile(
                path.join(outputDir, 'schematics', 'diagram.mmd'), 
                data.schematic, 
                'utf8'
            );
        }

        // Write BOM
        if (data.bom && Array.isArray(data.bom)) {
            const bomCsv = this._generateBOM(data.bom);
            await fs.writeFile(path.join(outputDir, 'docs', 'BOM.csv'), bomCsv, 'utf8');
        }

        // Write build guide
        if (data.buildGuide) {
            await fs.writeFile(
                path.join(outputDir, 'docs', 'BUILD_GUIDE.md'), 
                data.buildGuide, 
                'utf8'
            );
        }

        // Write metadata
        await fs.writeFile(
            path.join(outputDir, 'prototype.json'), 
            JSON.stringify(data, null, 2), 
            'utf8'
        );

        return outputDir;
    }

    async createZip(outputDir) {
        const zip = new JSZip();
        const zipName = `${path.basename(outputDir)}.zip`;
        const zipPath = path.join(path.dirname(outputDir), zipName);

        const addFilesToZip = async (dir, zipFolder) => {
            const files = await fs.readdir(dir, { withFileTypes: true });

            for (const file of files) {
                const fullPath = path.join(dir, file.name);
                const zipPath = zipFolder ? `${zipFolder}/${file.name}` : file.name;

                if (file.isDirectory()) {
                    const newFolder = zip.folder(zipPath);
                    await addFilesToZip(fullPath, zipPath);
                } else {
                    const content = await fs.readFile(fullPath);
                    zip.file(zipPath, content);
                }
            }
        };

        await addFilesToZip(outputDir, '');

        const content = await zip.generateAsync({ type: 'nodebuffer' });
        await fs.writeFile(zipPath, content);

        return zipPath;
    }

    _generateReadme(data) {
        const { overview, techStack, nextSteps } = data;

        return `# ${overview?.projectName || 'Prototype Project'}

${overview?.description || ''}

## Overview

- **Category:** ${overview?.category || 'N/A'}
- **Difficulty:** ${overview?.difficulty || 'N/A'}
- **Estimated Time:** ${overview?.estimatedTime || 'N/A'}

## Technology Stack

${techStack ? Object.entries(techStack).map(([k, v]) => `- **${k}:** ${Array.isArray(v) ? v.join(', ') : v}`).join('\n') : 'N/A'}

## Project Structure

\`\`\`
.
├── code/           # Source code files
├── docs/           # Documentation and guides
├── schematics/     # Diagrams and schematics
├── README.md       # This file
└── prototype.json  # Project metadata
\`\`\`

## Quick Start

1. Review the schematic in \`schematics/diagram.mmd\`
2. Check the BOM in \`docs/BOM.csv\` for hardware projects
3. Follow the build guide in \`docs/BUILD_GUIDE.md\`
4. Examine code in the \`code/\` directory

## Next Steps

${nextSteps ? nextSteps.map((step, i) => `${i + 1}. ${step}`).join('\n') : 'N/A'}

---

*Generated by ProtoForge*
`;
    }

    _generateBOM(bom) {
        const headers = ['Part Number', 'Description', 'Quantity', 'Unit Price', 'Supplier Link'];
        const rows = bom.map(item => [
            item.partNumber || '',
            item.description || '',
            item.quantity || '',
            item.unitPrice || '',
            item.supplierLink || ''
        ]);

        return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    }
}

module.exports = new Output();
